CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS countries (
  Code CHAR(2) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL 
); 

CREATE TABLE asn (
  id INT AUTO_INCREMENT PRIMARY KEY,
  start BIGINT NOT NULL,
  end BIGINT NOT NULL,
  asn BIGINT NOT NULL,
  description VARCHAR(255), 
  INDEX (start),
  INDEX (end)
); 
